//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro113_G3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int UID { get; set; }
        public string Name { get; set; }
        public string Email_User { get; set; }
        public string Bd_User { get; set; }
        public string GenderUser { get; set; }
        public string Description { get; set; }
        public string User_Id { get; set; }
        public string url { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
